## Understanding PyTorch

In this notebook, we explore pytorch fundamentals.

In [1]:
import torch
torch.__version__

'2.9.0'

In [2]:
torch.cuda.is_available()

False

In [3]:
print(torch.backends.mps.is_available())

True


## Scalars, vectors , matrices, and tensors

1. Scalar (0D Tensor): A single number. No direction, no dimensions

* Examples include : Temperature = 25°C, Loss value = 0.87, Learning rate = 0.001

* In Deep Learning we Use for: Loss values, Hyperparameters, Single outputs

2. Vector (1D Tensor): A list of numbers.It has magnitude + direction
* Examples: [2,5,7], Word embedding, Feature vector
* In Deep Learning we represents: Words (embeddings), Features of an input, Hidden states
3. Matrix (2D Tensor): A 2D grid of numbers (rows × columns)
* Example: [[1,2,3],[4,5,6]]
* In Deep Learning it used for: Batch of vectors, Weight matrices, Input data
* 3D Tensor → Image --> (Height × Width × Channels)
4. Tensor : A generalization of scalars, vectors, and matrices
Can have any number of dimensions
* 4D Tensor → Batch of images --> (Batch × Height × Width × Channels)



In [ ]:
tensor0d = torch.tensor(42)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
tensor3d = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]],
                         [[10,11,12], [13,14,15], [16,17,18]],
                         [[19,20,21], [22,23,24], [25,26,27]]])
print("Tensor 0D:", tensor0d)
print("Tensor 1D:", tensor1d)
print("Tensor 2D:", tensor2d)
print("Tensor 3D:", tensor3d)

Tensor 0D: tensor(42)
Tensor 1D: tensor([1, 2, 3])
Tensor 2D: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Tensor 3D: tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])


In [8]:
print(tensor0d.dtype)
print(tensor1d.dtype)
print(tensor2d.dtype)
print(tensor3d.dtype)
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(float_tensor.dtype)

torch.int64
torch.int64
torch.int64
torch.int64
torch.float32


In [12]:
float_tensor2 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(float_tensor2.dtype)
float_tensor3 = tensor1d.to(torch.float64)
print(float_tensor3.dtype)
print(float_tensor2)
print(float_tensor3)

torch.float32
torch.float64
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


In [13]:
print(tensor0d.shape)
print(tensor1d.shape)
print(tensor2d.shape)
print(tensor3d.shape)   

torch.Size([])
torch.Size([3])
torch.Size([3, 3])
torch.Size([3, 3, 3])


`Shape = structure of a tensor`
Shape tells you:
* Batch size
* Sequence length
* Embedding size

* Example: (batch_size, seq_len, embedding_dim)

In [20]:
tensor2D = torch.tensor([[1,2], [4,5], [7,8]])
print(tensor2D)
print(tensor2D.shape)

tensor([[1, 2],
        [4, 5],
        [7, 8]])
torch.Size([3, 2])


### What is Reshape

Reshape : Changes tensor shape without changing data

`Total elements must stay the same`

In [21]:
print(tensor2D.reshape(2,3))

tensor([[1, 2, 4],
        [5, 7, 8]])


### What is View?
* Similar to reshape 

BUT:
* Does NOT copy data
* Works only if tensor is contiguous in memory

In [29]:
print(tensor2D.view(2,3))

tensor([[1, 2, 4],
        [5, 7, 8]])


In [25]:
tensor3d.shape

torch.Size([3, 3, 3])

In [27]:
print(tensor3d.view(9,3))
print(tensor3d.view(9,3).shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])
torch.Size([9, 3])


In [28]:
print(tensor3d.reshape(9,3))
print(tensor3d.reshape(9,3).shape)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]])
torch.Size([9, 3])


## Transpose - Non contigous data

Transpose swaps rows and columns.
* Before: (6 × 3)
* After: (3 × 6)


This allows dot products between every pair of input vectors.

In [32]:
print(tensor2D.shape)
print(tensor2D.T.shape)

torch.Size([3, 2])
torch.Size([2, 3])


In [39]:
print(tensor2D.view(2,3))
print(tensor2D.T.view(2,3)) # This will work because the transposed tensor has the correct shape (2,3)

tensor([[1, 2, 4],
        [5, 7, 8]])
tensor([[1, 4, 7],
        [2, 5, 8]])


In [41]:
print(tensor2D.T.view(3,2)) # This will raise an error because the transposed tensor has a different shape (3,2) vs (2,3)  


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
print(tensor2D.T.reshape(3,2)) 


tensor([[1, 4],
        [7, 2],
        [5, 8]])


In [ ]:
x = torch.arange(6).reshape(2,3)
print(x)
x.T.view(6)   

tensor([[0, 1, 2],
        [3, 4, 5]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
x = torch.arange(6).reshape(3,2)
print(x)
x.T.view(2,3)  # works


tensor([[0, 1],
        [2, 3],
        [4, 5]])


tensor([[0, 2, 4],
        [1, 3, 5]])

In [47]:
print(x.T.reshape(2,3))  # also works because reshape can handle the change in shape as long as the total number of elements remains the same

tensor([[0, 3, 1],
        [4, 2, 5]])


```
* Shape → how data is arranged
* Reshape → rearrange safely
* View → rearrange efficiently (memory-level)
```

## Multiplications

What This Means

* Each element: result[i][j]=xi⋅xj
	​
* Measures similarity between vectors
* Used heavily in self-attention (QKᵀ)

In [49]:
print(tensor2d.matmul(tensor2d.T))  # This will perform matrix multiplication between tensor2d and its transpose

tensor([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]])


In [55]:
tensor1 = torch.tensor([[1,2], [3,4], [5,6] , [8,9]])
tensor2 = torch.tensor([[10,11], [12,13], [14,15], [16,17]])
print(tensor1)
print(tensor1.shape)
print(tensor2.T)
print(tensor2.T.shape)
tensor3 = tensor1.matmul(tensor2.T)  # This will perform matrix multiplication between tensor
print(tensor3, tensor3.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [8, 9]])
torch.Size([4, 2])
tensor([[10, 12, 14, 16],
        [11, 13, 15, 17]])
torch.Size([2, 4])
tensor([[ 32,  38,  44,  50],
        [ 74,  88, 102, 116],
        [116, 138, 160, 182],
        [179, 213, 247, 281]]) torch.Size([4, 4])


In [56]:
tensor3 = tensor1 @(tensor2.T)  # This will perform matrix multiplication between tensor
print(tensor3, tensor3.shape)

tensor([[ 32,  38,  44,  50],
        [ 74,  88, 102, 116],
        [116, 138, 160, 182],
        [179, 213, 247, 281]]) torch.Size([4, 4])


## Seeing models as computational Graphs

### Logistic regression forward pass

In [60]:
import torch.nn.functional as F
y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])
print(y, x1, w1, b)


tensor([1.]) tensor([1.1000]) tensor([2.2000]) tensor([0.])


In [62]:
z= x1*w1 + b
print(z)
a = torch.sigmoid(z)
print(a)
loss = F.binary_cross_entropy(a, y)
print(loss)


tensor([2.4200])
tensor([0.9183])
tensor(0.0852)
