## Attention mechanisms

In [33]:
import torch

# Your Journey starts with one step
inputs = torch.tensor(
    [[0.43, 0.15, 0.89], #x^1
    [0.55, 0.87, 0.66], #x^2
    [0.57, 0.85, 0.64], #x^3
    [0.22, 0.58, 0.33], #x^4
    [0.77, 0.25, 0.10], #x^5
    [0.05, 0.80, 0.55]] #x^6
)

In [34]:
print(inputs.shape)
print(inputs[0].shape)
print(inputs.shape[0])
print(inputs.shape[1])

torch.Size([6, 3])
torch.Size([3])
6
3


In [35]:
query = inputs[1]
attention_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attention_scores_2[i] = torch.dot(x_i, query)
print(attention_scores_2)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])


In [36]:
print(attention_scores_2.sum())
attention_weights_2_tmp = attention_scores_2 / attention_scores_2.sum()
print("Attention Weights (Tmp):", attention_weights_2_tmp)
print("Sum of Attention Weights (Tmp):", attention_weights_2_tmp.sum())

tensor(6.5617)
Attention Weights (Tmp): tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])
Sum of Attention Weights (Tmp): tensor(1.0000)


In [ ]:
def softmax_v1(x):
    exp_x = torch.exp(x)
    return exp_x / exp_x.sum(dim=0)

In [38]:
attention_weights_2_naive = softmax_v1(attention_scores_2)
print("Attention Weights (Naive):", attention_weights_2_naive)
print("Sum of Attention Weights (Naive):", attention_weights_2_naive.sum())

Attention Weights (Naive): tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum of Attention Weights (Naive): tensor(1.)


In [39]:
attention_weights = torch.softmax(attention_scores_2, dim=0)
print("Attention Weights (PyTorch):", attention_weights)
print("Sum of Attention Weights (PyTorch):", attention_weights.sum())

Attention Weights (PyTorch): tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
Sum of Attention Weights (PyTorch): tensor(1.)


In [40]:
query = inputs[1]
context_vector_2 = torch.empty(query.shape)
# context_vector = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vector_2 += attention_weights[i] * x_i
print("Context Vector:", context_vector_2)

Context Vector: tensor([0.4419, 0.6515, 0.5683])


### computing attention weights for all input tokens

In [41]:
attention_scores = torch.empty(inputs.shape[0],inputs.shape[0])
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attention_scores[i][j] = torch.dot(x_i, x_j)

print(attention_scores)


tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [42]:

attention_scores= inputs @ inputs.T
print(attention_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [43]:
attention_weights = torch.softmax(attention_scores, dim = -1)
print(attention_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [44]:
all_context_vectors = attention_weights @ inputs
print(all_context_vectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])
